popUp notificação
Sanja-Valley/api-6-frontend pull request #9
Opened 2023-05-14 19:00 UTC by alexiakarine

ta lindo :)

2023-05-15 23:43 UTC, guitambau requested changes

2023-05-15 23:43 UTC, guitambau commented on src/App.vue
> +    <!-- <div id="nav">
excluir esse comentario

2023-05-15 23:43 UTC, guitambau commented on src/views/Home.vue
> +    // document.querySelector("input").disabled = false
excluir esse também

2023-05-16 00:27 UTC, isarps approved these changes

2023-05-16 00:29 UTC, guitambau approved these changes

2023-05-16 00:29 UTC, merged